### ISSUE TITLE
Unable to build on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by Cinderella-Man** [TrezarCoin/TrezarCoin#11] opened 2018-02-02 05:05 UTC
Hi,

I'm getting to last step in the guide (https://trezarcoin.com/wp-content/uploads/2017/09/TrezarCoins-Rasberry-Pi-Compile-Final.pdf)

and getting following: https://pastebin.com/JXb2QJji

Could you please advise?

**Comment by Zeykit-Dev** [comment] 2018-02-09 21:47
Same problem here...

**Comment by dtwpt** [comment] 2018-02-09 22:02
hello i believe the issue is that you are missing openssl, can you please install that before bulding the wallet?

**Comment by Zeykit-Dev** [comment] 2018-02-09 22:30
Hi, openssl was already installed :(

2018-02-09 23:02 GMT+01:00 Miguel Sousa <notifications@github.com>:

**Comment by aciddude** [comment] 2018-03-03 16:46
At time of writing, Raspbian (stretch) comes with openssl 1.1.0f
We need 1.0.X,  so we need to use the backports and compile ourselves since the Debian version for jessie was compiled for ARMv6 and we need ARMv7 for our rPi3.


The above applies only if you're using Raspbian 9 (stretch)

**Comment by ChristopherRush** [comment] 2018-03-12 12:35
I have done the above but is now receiving the following error:
https://nofile.io/f/1ZDgQhKdPhS/Screenshot+2018-03-12+12.25.03.png

**Comment by aciddude** [comment] 2018-03-12 15:24
Hi Guys, 

try out this build guide here

https://walton.io/trezarcoin-raspberry-pi-3-build-guide-a82b622e03c2

**Comment by ChristopherRush** [comment] 2018-03-13 10:56
The guide is full of syntax errors and fails to compile openssl.

**Comment by Cinderella-Man** [comment] 2018-03-13 11:00
As I can see it a little bit tricky to do it consistently even on Raspberry Pi - would it be possible to provide *official* docker image(possibly from `scratch`)?

**Comment by aciddude** [comment] 2018-03-13 12:05
@ChristopherRush  - did you follow the walton.io guide ? 

you have to specify your openssl and bdb libs in your qmake command. 

```
qmake “USE_QRCODE=1” “USE_UPNP=1” “OPENSSL_INCLUDE_PATH=/home/pi/openssl/include” “OPENSSL_LIB_PATH=/home/pi/openssl/lib” “BDB_INCLUDE_PATH=/usr/local/BerkeleyDB.4.8/include” “BDB_LIB_PATH=/usr/local/BerkeleyDB.4.8/lib”
make

```

**Comment by aciddude** [comment] 2018-03-18 16:18
I've left a complete guide that I have tested against new installs of Stretch Raspbian 9

https://github.com/TrezarCoin/TrezarCoin/wiki/Raspberry-Pi---Build-Guide

**Comment by ChristopherRush** [comment] 2018-03-18 16:24
Thanks, I'll check it out sometime next week.

**Comment by ChristopherRush** [comment] 2018-03-19 11:47
@aciddude Guide is perfect, everything installs ok. Thanks for taking the time to upload it!

**Comment by aciddude** [comment] 2018-03-19 12:02
@ChristopherRush  - No worries. Glad you've got it working. 


Closing this now as the guide is reproducible.

**Closed by aciddude** 2018-03-19 12:02 UTC
